# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
 - jekyll-seo-tag
 - jekyll-sitemap
# Site settings
title: hatorikibble
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  nicht-bibliothekarischer Technikkram
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hatorikibble.github.io" # the base hostname & protocol for your site
twitter_username: hatorikibble
github_username:  hatorikibble

# Build settings
markdown: kramdown
